In [1]:
import pandas as pd
import numpy as np

## Filter function

In [38]:
def filterCountry(data):
    lst = ["Estonia","Latvia","Lithuania","Greece","Cyprus",
           "Vietnam","Mexico","Brazil","Algeria","India","Russian Federation",
           "Ukraine","Sri Lanka","Venezuela, RB","Nigeria","Colombia",
           "Haiti","Madagascar","Burundi","Cambodia","Yemen, Rep.",
           "France","Germany","United Kingdom","United States","Canada","Japan"]
    for i in range(len(data)):
        if data["Country Name"][i] not in lst:
            data.drop(i,axis=0,inplace=True)

In [39]:
def cut(data):
    column = ["Country Name", "Country Code","2018","2019","2020","2021"]
    for i in np.array(data.columns):
        if i not in column:
            data.drop(i,axis=1,inplace=True)

---

### Employ

In [43]:
EfeILO = pd.read_csv("employ/female_modeledILO/main.csv")
Efenat = pd.read_csv("employ/female_national/main.csv")
EmaILO = pd.read_csv("employ/male_modeledILO/main.csv")
Emanat = pd.read_csv("employ/male_national/main.csv")

# Apply filter
filterCountry(EfeILO)
filterCountry(Efenat)
filterCountry(EmaILO)
filterCountry(Emanat)
# Cut data
cut(EfeILO)
cut(Efenat)
cut(EmaILO)
cut(Emanat)

In [62]:
EfeILO.fillna(0,inplace=True)
EfeILO.to_csv("EfeILO.csv",index=False)
EfeILO = pd.read_csv("EfeILO.csv")
EfeILO

,Country Name,Country Code,2018,2019,2020,2021
0,Burundi,BDI,78.902000,78.917000,78.084999,77.863998
1,Brazil,BRA,45.251999,45.881001,40.056000,40.425999
2,Canada,CAN,57.932999,58.217999,53.929001,56.356998
3,Colombia,COL,50.290001,48.862000,40.695999,42.619999
4,Cyprus,CYP,52.205002,52.713001,52.117001,52.651001
5,Germany,DEU,54.339001,55.046001,54.919998,55.043999
6,Algeria,DZA,13.601000,13.507000,12.132000,12.212000
7,Estonia,EST,54.308998,54.827000,53.749001,53.967999
8,France,FRA,46.764999,46.973999,46.596001,47.738998
9,United Kingdom,GBR,55.738998,56.396000,56.167999,55.548000
10,Greece,GRC,33.507000,34.799999,34.828999,35.138000
11,Haiti,HTI,52.070999,51.924000,49.097000,49.179001
12,India,IND,19.438999,20.134001,17.577999,18.362000
13,Japan,JPN,51.301998,52.132999,51.841999,51.946999
14,Cambodia,KHM,76.127998,75.980003,73.526001,73.429001
15,Sri Lanka,LKA,30.915001,30.653999,28.030001,28.304001
16,Lithuania,LTU,53.469002,54.143002,52.978001,53.056000
17,Latvia,LVA,52.214001,52.661999,52.070999,50.785999
18,Madagascar,MDG,82.211998,82.252998,78.873001,79.342003
19,Mexico,MEX,41.810001,42.977001,39.132000,41.966999
20,Nigeria,NGA,45.375000,45.429001,43.508999,43.707001
21,Russian Federation,RUS,53.191002,52.916000,52.084000,51.748001
22,Ukraine,UKR,45.861000,45.395000,43.924999,43.932999
23,United States,USA,54.077000,54.553001,50.768002,52.326000
24,"Venezuela, RB",VEN,39.943001,33.997002,31.792000,31.743999
25,Vietnam,VNM,69.691002,68.919998,67.699997,68.181000
26,"Yemen, Rep.",YEM,4.571000,4.602000,4.530000,4.419000

In [61]:
Efenat.fillna(0,inplace=True)
Efenat.to_csv("Efenat.csv",index=False)
Efenat = pd.read_csv("Efenat.csv")
Efenat

,Country Name,Country Code,2018,2019,2020,2021
0,Burundi,BDI,0.000000,0.000000,0.000000,0.000000
1,Brazil,BRA,46.230000,46.930000,41.340000,0.000000
2,Canada,CAN,57.939999,58.220001,53.930000,56.259998
3,Colombia,COL,50.290001,48.860001,40.700001,0.000000
4,Cyprus,CYP,52.360001,52.880001,52.279999,0.000000
5,Germany,DEU,54.320000,55.029999,54.910000,0.000000
6,Algeria,DZA,0.000000,0.000000,0.000000,0.000000
7,Estonia,EST,54.340000,54.849998,53.759998,0.000000
8,France,FRA,46.770000,46.980000,46.599998,0.000000
9,United Kingdom,GBR,55.740002,56.389999,0.000000,0.000000
10,Greece,GRC,33.580002,34.869999,34.900002,0.000000
11,Haiti,HTI,0.000000,0.000000,0.000000,0.000000
12,India,IND,19.730000,20.450001,25.040001,0.000000
13,Japan,JPN,51.330002,52.189999,51.830002,52.180000
14,Cambodia,KHM,0.000000,61.610001,0.000000,0.000000
15,Sri Lanka,LKA,31.180000,31.900000,0.000000,0.000000
16,Lithuania,LTU,53.470001,54.119999,52.930000,0.000000
17,Latvia,LVA,52.230000,52.660000,52.070000,0.000000
18,Madagascar,MDG,0.000000,0.000000,0.000000,0.000000
19,Mexico,MEX,41.970001,43.189999,39.259998,0.000000
20,Nigeria,NGA,0.000000,45.630001,0.000000,0.000000
21,Russian Federation,RUS,53.189999,52.910000,52.070000,0.000000
22,Ukraine,UKR,52.529999,45.380001,43.759998,0.000000
23,United States,USA,54.889999,55.360001,51.509998,53.169998
24,"Venezuela, RB",VEN,0.000000,0.000000,0.000000,0.000000
25,Vietnam,VNM,69.720001,62.509998,60.430000,0.000000
26,"Yemen, Rep.",YEM,0.000000,0.000000,0.000000,0.000000

In [63]:
EmaILO.fillna(0,inplace=True)
EmaILO.to_csv("EmaILO.csv",index=False)
EmaILO = pd.read_csv("EmaILO.csv")
EmaILO

,Country Name,Country Code,2018,2019,2020,2021
0,Burundi,BDI,76.435997,76.390999,75.563004,75.693001
1,Brazil,BRA,64.413002,64.919998,59.353001,60.115002
2,Canada,CAN,65.362000,65.865997,62.105999,64.377998
3,Colombia,COL,74.785004,73.393997,66.609001,69.023003
4,Cyprus,CYP,62.205002,64.375000,63.839001,65.082001
5,Germany,DEU,64.278999,65.098999,63.748001,63.488998
6,Algeria,DZA,61.020000,61.043999,57.347000,57.750000
7,Estonia,EST,67.408997,67.726997,65.676003,65.552002
8,France,FRA,54.796001,54.609001,54.060001,54.834999
9,United Kingdom,GBR,65.575996,65.496002,63.966000,63.917999
10,Greece,GRC,50.707001,51.573002,50.969002,51.356998
11,Haiti,HTI,61.841000,61.779999,60.049000,60.165001
12,India,IND,69.625000,69.318001,63.446999,65.641998
13,Japan,JPN,69.293999,69.620003,69.218002,68.894997
14,Cambodia,KHM,86.682999,86.606003,85.547997,85.476997
15,Sri Lanka,LKA,70.212997,69.375000,65.324997,65.839996
16,Lithuania,LTU,62.948002,63.096001,62.494999,62.201000
17,Latvia,LVA,62.615002,63.130001,62.312000,61.271999
18,Madagascar,MDG,87.153000,87.004997,85.195000,85.399002
19,Mexico,MEX,74.616997,74.205002,68.016998,72.030998
20,Nigeria,NGA,55.220001,54.978001,52.931999,53.296001
21,Russian Federation,RUS,67.819000,67.269997,66.113998,66.237999
22,Ukraine,UKR,57.985001,59.316002,57.450001,57.796001
23,United States,USA,65.220001,65.487999,61.377998,62.686001
24,"Venezuela, RB",VEN,69.771004,67.070000,63.613998,63.889999
25,Vietnam,VNM,79.963997,79.125999,78.427002,77.662003
26,"Yemen, Rep.",YEM,59.752998,59.979000,59.195999,59.219002

In [64]:
Emanat.fillna(0,inplace=True)
Emanat.to_csv("Emanat.csv",index=False)
Emanat = pd.read_csv("Emanat.csv")
Emanat

,Country Name,Country Code,2018,2019,2020,2021
0,Burundi,BDI,0.000000,0.000000,0.000000,0.000000
1,Brazil,BRA,66.250000,66.879997,62.009998,0.000000
2,Canada,CAN,65.360001,65.870003,62.110001,64.290001
3,Colombia,COL,74.779999,73.389999,66.620003,0.000000
4,Cyprus,CYP,62.380001,64.570000,64.029999,0.000000
5,Germany,DEU,64.250000,65.089996,63.740002,0.000000
6,Algeria,DZA,0.000000,0.000000,0.000000,0.000000
7,Estonia,EST,67.440002,67.750000,65.680000,0.000000
8,France,FRA,54.810001,54.610001,54.070000,0.000000
9,United Kingdom,GBR,65.580002,65.500000,0.000000,0.000000
10,Greece,GRC,50.799999,51.660000,51.060001,0.000000
11,Haiti,HTI,0.000000,0.000000,0.000000,0.000000
12,India,IND,70.650002,70.389999,72.169998,0.000000
13,Japan,JPN,69.320000,69.660004,69.279999,69.150002
14,Cambodia,KHM,0.000000,76.209999,0.000000,0.000000
15,Sri Lanka,LKA,70.779999,70.550003,0.000000,0.000000
16,Lithuania,LTU,62.950001,63.080002,62.439999,0.000000
17,Latvia,LVA,62.630001,63.119999,62.310001,0.000000
18,Madagascar,MDG,0.000000,0.000000,0.000000,0.000000
19,Mexico,MEX,74.900002,74.570000,68.269997,0.000000
20,Nigeria,NGA,0.000000,59.630001,0.000000,0.000000
21,Russian Federation,RUS,67.820000,67.269997,66.089996,0.000000
22,Ukraine,UKR,62.110001,59.290001,57.180000,0.000000
23,United States,USA,66.330002,66.580002,62.389999,63.900002
24,"Venezuela, RB",VEN,0.000000,0.000000,0.000000,0.000000
25,Vietnam,VNM,80.000000,75.580002,73.720001,0.000000
26,"Yemen, Rep.",YEM,0.000000,0.000000,0.000000,0.000000

---

### Unemployment

In [60]:
UfeILO = pd.read_csv("unemploy/female_ILO/main.csv")
Ufenat = pd.read_csv("unemploy/female_national/main.csv")
UmaILO = pd.read_csv("unemploy/male_ILO/main.csv")
Umanat = pd.read_csv("unemploy/male_national/main.csv")

# Apply filter
filterCountry(UfeILO)
filterCountry(Ufenat)
filterCountry(UmaILO)
filterCountry(Umanat)
# Cut data
cut(UfeILO)
cut(Ufenat)
cut(UmaILO)
cut(Umanat)

In [65]:
UfeILO.fillna(0,inplace=True)
UfeILO.to_csv("UfeILO.csv",index=False)
UfeILO = pd.read_csv("UfeILO.csv")

Ufenat.fillna(0,inplace=True)
Ufenat.to_csv("Ufenat.csv",index=False)
Ufenat = pd.read_csv("Ufenat.csv")

UmaILO.fillna(0,inplace=True)
UmaILO.to_csv("UmaILO.csv",index=False)
UmaILO = pd.read_csv("UmaILO.csv")

Umanat.fillna(0,inplace=True)
Umanat.to_csv("Umanat.csv",index=False)
Umanat = pd.read_csv("Umanat.csv")

---